---
- name: create user
  user: name="{{item.name}}" uid="{{item.uid}}" group="{{item.group}}" shell="{{item.shell}}" password="{{item.password}}" state="{{item.state}}"
  with_items: users
  tags: account

- name: add authorized key
  authorized_key: user={{item.name}} key="{{item.key}}"
  with_items: users
  tags: account

- name: add sudoers
  copy: src=sudoers/ymatsumo dest=/etc/sudoers.d/ymatsumo owner=root group=root mode=440 validate='visudo -cf %s'
  tags: account
